### ISSUE TITLE
Add shortcuts action to display the balance

### ISSUE THREAD

**Issue by Robot8A** [schorschii/MensaGuthaben-iOS#2]
The idea is that the users can read the card via a shortcut to faster know the card balance.
A use case could be to set up an automation that when the mensa card is detected, it runs this shortcut.

**Comment by schorschii** [comment]
This is a great idea, unfortunately I don't have an appropriate iPhone to test this. The NFC shortcut options seems to be [only available on iPhone XS and newer](https://developer.apple.com/forums/thread/118936). I only have an iPhone 8 here for testing purposes.
If someone else implements it, I'll happily accept the pull request :)

**Comment by schorschii** [comment]
CC @PaulS94
